# Generated by Django 3.2.2 on 2021-09-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexmain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='road',
            name='title',
        ),
        migrations.AddField(
            model_name='road',
            name='czas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='droga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='odcinek',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='podpisane',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='termin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='wykonawca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
