# Generated by Django 3.2.2 on 2021-09-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexmain', '0002_auto_20210917_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='koszt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
