# Generated by Django 3.2.2 on 2021-09-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexmain', '0004_remove_road_termin'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='map1_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='map1_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='map2_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='map2_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
