# Generated by Django 3.2.2 on 2021-10-07 21:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexmain', '0006_road_data_ukonczenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='opis',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
