# Generated by Django 3.2.2 on 2021-10-08 15:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexmain', '0007_road_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='opis',
            field=ckeditor.fields.RichTextField(blank=True, default='w budowie', null=True),
        ),
    ]
